// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxhtcdyxmtfyvanqhaty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4aHRjZHl4bXRmeXZhbnFoYXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjU5NTEsImV4cCI6MjA2NTU0MTk1MX0.EdfLsNbHiEwx65x1gfv6OOLnvKKe8EBZYKsmJ9f5L2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);